---
# tasks file for get_hosts
- name: init list_temp_api_response
  set_fact:
    list_temp_api_response: []
    
- block:
    - name: include get_individual_host.yml for hosts
      include_tasks: get_individual_host.yml
      loop: "{{ list_of_hosts }}"

    - name: show results
      debug:
        var: list_temp_api_response

    - name: set list_temp_api_response back to list_api_reponse
      set_fact:
        list_api_response: "{{ list_temp_api_response }}"
  when: False #"'all' not in list_of_hosts"

- block:
    # - name: set api to get all the host details from the organization
    #   set_fact:
    #     api: /api/v2/organizations/?name={{ user_org | urlencode }}
  
    # - name: include get_aap_api_reponse role to fetch api details
    #   include_role: 
    #     name: get_aap_api_response

    - name: set api to get all the host details
      set_fact:
        api: "/api/v2/hosts/?page_size=100"     #organization specific is not avaiable in api like other content
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response
  when: "'all' in list_of_hosts"

- name: assign the list_api_response to list_api_details_hosts
  set_fact:
    list_api_details_hosts: "{{ list_api_response }}"

- debug:
    var: list_api_details_hosts | length

- name: Get survey variables for hosts
  include_tasks: extract_host_details.yml
  loop: "{{ list_api_details_hosts }}"

- name: print invalid host names
  debug:
    var: list_invalid_hosts
  when: list_invalid_hosts is defined and list_invalid_hosts | length > 0

- name: Write host details to YAML file
  template:
    src: host_details.yml.j2
    dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_host_details.yml"
  when: (generate_yml_file and host_list) | length > 0 and (append_or_create == 'create')


- name: Append host details to YAML file
  block:
    - name: Append host details to YAML file
      template:
        src: host_details.yml.j2
        dest: "{{ playbook_dir }}/temp_host_details.yml"

    - name: Read old YAML file content
      include_vars:
        file: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_host_details.yml"
        name: old_host_yaml
      ignore_errors: true

    - name: print the old list
      debug:
        var: old_host_yaml
      when: old_host_yaml is defined

    - name: Read new temporary YAML file content
      include_vars:
        file: "{{ playbook_dir }}/temp_host_details.yml"
        name: new_temp_host_yaml

    - name: print the newly fetched list
      debug:
        var: new_temp_host_yaml

    - name: Compare old_host_yaml with new_temp_host_yaml
      set_fact:
        updated_host_yaml: "{{ (new_temp_host_yaml.controller_hosts) | union(old_host_yaml.controller_hosts ) | unique(attribute='name') }}"
      when: old_host_yaml is defined and old_host_yaml.controller_hosts is defined

    - name: Assign the updated host list
      set_fact:
        host_list: "{{ updated_host_yaml }}"
      when: old_host_yaml is defined and old_host_yaml.controller_hosts is defined

    - name: Assign the new host list
      set_fact:
        host_list: "{{ new_temp_host_yaml.controller_hosts }}"
      when: old_host_yaml is not defined and old_host_yaml.controller_hosts is not defined

    - name: show the host list
      debug:
        var: host_list
  
    - name: Write host details to YAML file
      template:
        src: append_hosts.yml.j2
        dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_host_details.yml"

  when: (generate_yml_file and host_list) | length > 0 and (append_or_create == 'append')