- name: Get GitHub user information
  uri:
    url: "https://api.github.com/user"
    method: GET
    validate_certs: "{{ github_validate_certs | default(false) }}"
    headers:
      Authorization: "token {{ github_PAT }}"
    return_content: yes
  register: github_user_info
  until: github_user_info.status == 200
  retries: 3
  delay: 5
  no_log: true