---
- name: Get Open Pull Requests
  uri:
    url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/pulls?state=open"
    method: GET
    validate_certs: "{{ github_validate_certs | default(false) }}"
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "token {{ github_PAT }}"
  register: list_open_pull_requests
  loop: "{{ list_repo_name }}"
  loop_control:
    loop_var: repo_name
  until: list_open_pull_requests.status == 200
  retries: 3
  delay: 5
  ignore_errors: yes
  no_log: true