---
# tasks file for get_projects
- name: init list_temp_api_response
  set_fact:
    list_temp_api_response: []
    
- block:
    - name: include get_individual_project.yml for projects
      include_tasks: get_individual_project.yml
      loop: "{{ list_of_projects }}"

    - name: show results
      debug:
        var: list_temp_api_response

    - name: set list_temp_api_response back to list_api_reponse
      set_fact:
        list_api_response: "{{ list_temp_api_response }}"
  when: "'all' not in list_of_projects"

- block:
    - name: set api to get all the project details from the organization
      set_fact:
        api: /api/v2/organizations/?name={{ user_org | urlencode }}
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response

    - name: set api to get all the project details
      set_fact:
        api: "{{ list_api_response[0].related.projects }}"
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response
  when: "'all' in list_of_projects"

- name: assign the list_api_response to list_api_details_projects
  set_fact:
    list_api_details_projects: "{{ list_api_response }}"

- debug:
    var: list_api_details_projects | length

- name: Get survey variables for projects
  include_tasks: extract_project_details.yml
  loop: "{{ list_api_details_projects }}"

- name: print invalid project names
  debug:
    var: list_invalid_projects
  when: list_invalid_projects is defined and list_invalid_projects | length > 0

- name: Write project details to YAML file
  template:
    src: project_details.yml.j2
    dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_project_details.yml"
  when: (generate_yml_file and project_list) | length > 0 and (append_or_create == 'create')


- name: Append project details to YAML file
  block:
    - name: Append project details to YAML file
      template:
        src: project_details.yml.j2
        dest: "{{ playbook_dir }}/temp_project_details.yml"

    - name: Read old YAML file content
      include_vars:
        file: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_project_details.yml"
        name: old_project_yaml
      ignore_errors: true

    - name: print the old list
      debug:
        var: old_project_yaml
      when: old_project_yaml is defined

    - name: Read new temporary YAML file content
      include_vars:
        file: "{{ playbook_dir }}/temp_project_details.yml"
        name: new_temp_project_yaml

    - name: print the newly fetched list
      debug:
        var: new_temp_project_yaml

    - name: Compare old_project_yaml with new_temp_project_yaml
      set_fact:
        updated_project_yaml: "{{ (new_temp_project_yaml.controller_projects) | union(old_project_yaml.controller_projects ) | unique(attribute='name') }}"
      when: old_project_yaml is defined and old_project_yaml.controller_projects is defined

    - name: Assign the updated project list
      set_fact:
        project_list: "{{ updated_project_yaml }}"
      when: old_project_yaml is defined and old_project_yaml.controller_projects is defined

    - name: Assign the new project list
      set_fact:
        project_list: "{{ new_temp_project_yaml.controller_projects }}"
      when: old_project_yaml is not defined and old_project_yaml.controller_projects is not defined

    - name: show the project list
      debug:
        var: project_list
  
    - name: Write project details to YAML file
      template:
        src: project_details.yml.j2
        dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_project_details.yml"

  when: (generate_yml_file and project_list) | length > 0 and (append_or_create == 'append')  

