---
# tasks file for get_job_templates
- name: init list_temp_api_response
  set_fact:
    list_temp_api_response: []
    
- block:
    - name: include get_individual_job_template.yml for job templates
      include_tasks: get_individual_job_template.yml
      loop: "{{ list_of_job_templates }}"

    - name: show results
      debug:
        var: list_temp_api_response

    - name: set list_temp_api_response back to list_api_reponse
      set_fact:
        list_api_response: "{{ list_temp_api_response }}"
  when: "'all' not in list_of_job_templates"

- block:
    - name: set api to get all the job template details from the organization
      set_fact:
        api: /api/v2/organizations/?name={{ user_org | urlencode }}
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response

    - name: set api to get all the job template details
      set_fact:
        api: "{{ list_api_response[0].related.job_templates }}"
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response
  when: "'all' in list_of_job_templates"

- name: assign the list_api_response to list_api_details_job_templates
  set_fact:
    list_api_details_job_templates: "{{ list_api_response }}"

- debug:
    var: list_api_details_job_templates | length

- name: Get survey variables for job templates
  include_tasks: extract_job_template_details.yml
  loop: "{{ list_api_details_job_templates }}"

- name: print invalid job template names
  debug:
    var: list_invalid_job_templates
  when: list_invalid_job_templates is defined and list_invalid_job_templates | length > 0

- name: Write job_template details to YAML file
  template:
    src: job_template_details.yml.j2
    dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_job_template_details.yml"
  when: (generate_yml_file and job_template_list) | length > 0 and (append_or_create == 'create')


- name: Append job_template details to YAML file
  block:
    - debug:
        var: job_template_list

    - name: Append job_template details to YAML file
      template:
        src: job_template_details.yml.j2
        dest: "{{ playbook_dir }}/temp_job_template_details.yml"

    - name: Read old YAML file content
      include_vars:
        file: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_job_template_details.yml"
        name: old_job_template_yaml
      ignore_errors: yes
########################################################
    - name: Process extra vars in old content
      include_tasks: process_extra_vars.yml
      loop: "{{ old_job_template_yaml.controller_templates }}"
      when: old_job_template_yaml is defined and old_job_template_yaml.controller_templates is defined

    - name: Assign the processed content list to old_job_template_yaml.controller_templates
      set_fact:
        old_job_template_yaml:
          controller_templates: "{{ list_temp_content }}"
      when: (list_temp_content is defined) and (list_temp_content | length > 0)

    - name: print the old list
      debug:
        var: old_job_template_yaml
      when: old_job_template_yaml is defined

    - name: Read new temporary YAML file content
      include_vars:
        file: "{{ playbook_dir }}/temp_job_template_details.yml"
        name: new_temp_job_template_yaml

    - name: init list_temp_content
      set_fact:
        list_temp_content: []

    - name: Process extra vars in old content
      include_tasks: process_extra_vars.yml
      loop: "{{ new_temp_job_template_yaml.controller_templates }}"
      when: new_temp_job_template_yaml is defined and new_temp_job_template_yaml.controller_templates is defined

    - name: Assign the processed content list to old_job_template_yaml.controller_templates
      set_fact:
        new_temp_job_template_yaml:
          controller_templates: "{{ list_temp_content }}"

    - name: print the newly fetched list
      debug:
        var: new_temp_job_template_yaml

    - name: Compare old_job_template_yaml with new_temp_job_template_yaml
      set_fact:
        updated_job_template_yaml: "{{ (new_temp_job_template_yaml.controller_templates) | union(old_job_template_yaml.controller_templates ) | unique(attribute='name') }}"
      when: old_job_template_yaml is defined and old_job_template_yaml.controller_templates is defined

    - name: Assign the updated job template list
      set_fact:
        job_template_list: "{{ updated_job_template_yaml }}"
      when: old_job_template_yaml is defined and old_job_template_yaml.controller_templates is defined

    - name: Assign the new job template list
      set_fact:
        job_template_list: "{{ new_temp_job_template_yaml.controller_templates }}"
      when: old_job_template_yaml is not defined and old_job_template_yaml.controller_templates is not defined

    - name: show the job template list
      debug:
        var: job_template_list
  
    - name: Write job_template details to YAML file
      template:
        src: append_job_templates.yml.j2
        dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_job_template_details.yml"

  when: (generate_yml_file and job_template_list) | length > 0 and (append_or_create == 'append')  

