---
# tasks file for get_workflows
- name: init list_temp_api_response
  set_fact:
    list_temp_api_response: []

- block:
    - name: include get_individual_workflow.yml for job templates
      include_tasks: get_individual_workflow.yml
      loop: "{{ list_of_workflows }}"

    - name: show results
      debug:
        var: list_temp_api_response

    - name: set list_temp_api_response back to list_api_reponse
      set_fact:
        list_api_response: "{{ list_temp_api_response }}"
  when: "'all' not in list_of_workflows"

- block:
    - name: set api to get all the workflow details from the organization
      set_fact:
        api: /api/v2/organizations/?name={{ user_org | urlencode }}
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response

    - name: set api to get all the job template details
      set_fact:
        api: "{{ list_api_response[0].related.workflow_job_templates }}"
  
    - name: include get_aap_api_reponse role to fetch api details
      include_role: 
        name: get_aap_api_response
  when: "'all' in list_of_workflows"

- name: assign the list_api_response to list_api_details_workflows
  set_fact:
    list_api_details_workflows: "{{ list_api_response }}"

- debug:
    var: list_api_details_workflows | length

- name: Get survey variables for job templates
  include_tasks: extract_workflow_details.yml
  loop: "{{ list_api_details_workflows }}"

- name: print invalid job template names
  debug:
    var: list_invalid_workflows
  when: list_invalid_workflows is defined and list_invalid_workflows | length > 0

- name: Write workflow details to YAML file
  template:
    src: workflow_job_template_details.yml.j2
    dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_workflow_job_template_details.yml"
  when: (generate_yml_file and workflow_list) | length > 0 and (append_or_create == 'create')


- name: Append workflow details to YAML file
  block:
    - name: Append workflow details to YAML file
      template:
        src: workflow_job_template_details.yml.j2
        dest: "{{ playbook_dir }}/temp_workflow_job_template_details.yml"

    - name: Read old YAML file content
      include_vars:
        file: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_workflow_job_template_details.yml"
        name: old_workflow_yaml
      ignore_errors: true

    - name: print the old list
      debug:
        var: old_workflow_yaml
      when: old_workflow_yaml is defined

    - name: Read new temporary YAML file content
      include_vars:
        file: "{{ playbook_dir }}/temp_workflow_job_template_details.yml"
        name: new_temp_workflow_yaml

    - name: print the newly fetched list
      debug:
        var: new_temp_workflow_yaml

    - name: Compare old_workflow_yaml with new_temp_workflow_yaml
      set_fact:
        updated_workflow_yaml: "{{ new_temp_workflow_yaml.controller_workflows | union(old_workflow_yaml.controller_workflows)  | unique(attribute='name') }}"
      when: old_workflow_yaml is defined and old_workflow_yaml.controller_workflows is defined
      

    - name: Assign the updated workflow list
      set_fact:
        workflow_list: "{{ updated_workflow_yaml }}"
      when: old_workflow_yaml is defined and old_workflow_yaml.controller_workflows is defined

    - name: Assign the new workflow list
      set_fact:
        workflow_list: "{{ new_temp_workflow_yaml.controller_workflows }}"
      when: old_workflow_yaml is not defined and old_workflow_yaml.controller_workflows is not defined

    - name: Show the workflow list
      debug:
        var: workflow_list
  
    - name: Write workflow details to YAML file
      template:
        src: append_workflows.yml.j2
        dest: "{{ playbook_dir }}/{{ repo }}/{{ user_org | lower }}_workflow_job_template_details.yml"

  when: (generate_yml_file and workflow_list) | length > 0 and (append_or_create == 'append')  

